# Create scene
/vis/scene/create

# Open viewer
/vis/open OGL
/vis/drawVolume

# Camera setup
/vis/viewer/set/viewpointThetaPhi 30 30
/vis/viewer/zoom 1.0

# Rendering style
/vis/viewer/set/style surface
/vis/viewer/set/hiddenEdge 1

# Axes
/vis/scene/add/axes 0 0 0 1 m

# Trajectories
/vis/modeling/trajectories/create/drawByParticleID
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate 100

# Auto refresh
/vis/viewer/set/autoRefresh true
